name = "alikernel-auth"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "8099cb330a0c4296bdea5e163aa42e72"
